version: '3.8'

networks:
  app-net:
    driver: bridge



services:
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "3001:3001"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
      - OTEL_SERVICE_NAME=order-service
    networks:
      - app-net
    depends_on:
      - rabbitmq

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "3002:3002"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
      - OTEL_SERVICE_NAME=inventory-service
    networks:
      - app-net
    depends_on:
      - rabbitmq

  notification-service:
    build: ./notification-service
    container_name: notification-service
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - OTEL_SERVICE_NAME=notification-service
    networks:
      - app-net
    depends_on:
      - rabbitmq

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - app-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-net

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    networks:
      - app-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - app-net
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app-net

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    networks:
      - app-net
    depends_on:
      - loki
