CREATE TABLE IF NOT EXISTS realtime_views (
    video_id VARCHAR(50) PRIMARY KEY,
    views INT NOT NULL DEFAULT 0,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS batch_views (
    video_id VARCHAR(50) PRIMARY KEY,
    views INT NOT NULL DEFAULT 0,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
